volumes:
  data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  
  server:
    build: .
    image: server
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@postgres:5432/db?schema=public"
    volumes:
      - .:/app:rw
    ports:
      - 3000:3000
    depends_on:
      - postgres

