volumes:
  data:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=psqldev
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:psqldev@postgres:5432
    volumes:
      - ./dist:/app/src/dist:ro
      - ./prisma:/app/src/prisma:ro
      - ./.env:/app/src/.env:ro
    command: bash -c "npx prisma db push && npx nodemon dist/server.js"
    ports:
      - 3000:3000
    depends_on:
      - postgres