volumes:
  data:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=psqldev
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  app:
    build: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:psqldev@localhost:5432
    volumes:
      - ./dist:/app/src/dist:ro
    command: npx node dist/server.js
    ports:
      - 3000:3000
    depends_on:
      - postgres