volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql

  server:
    container_name: shop-helper-server
    build: .
    ports:
      - "8080:8080"
    command: bash -c "npx prisma db push && node server.js"
    depends_on:
      - postgres

