volumes:
  data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      
  api:
    container_name: node-api-container
    build: .
    image: node-api:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/db?schema=public
      - NODE_ENV=development
    volumes:
      - ./dist:/app/src/dist:rw
      - ./package.json:/app/src/package.json:rw
      - ./prisma/:/app/src/prisma:rw
      - ./tsconfig.json:/app/src/tsconfig.json:rw
    command: sh -c "yarn && npx nodemon dist/server.js"
    ports:
      - 3000:3000
    depends_on:
      - postgres
